actions:
  - name: up
    description: "Starts the development environment for this project"
    command: "nix develop -c tmuxide"
  - name: build
    description: "Build the project"
    command: "go build"
  - name: run
    description: "Run the project"
    command: "go run . %*"
  - name: test
    description: "Run project test suite"
    command: "go test"
  - name: qmpSock 
    command: "nc -U ./.vmlab/myVM/control.sock"
    description: "Connect to monitor socket on ubuntu vm."
  - name: guestSock
    command: "nc -U ./.vmlab/myVM/guest.sock"
    description: "Connect to guest agent socket on ubuntu vm."

