name: Reject Pull Requests

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  reject:
    runs-on: ubuntu-latest
    steps:
      - name: Reject PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '❌ This repository does not accept pull requests as it is an archive of deprecated projects.'
            });
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              state: 'closed'
            });
